void copper_init();
UWORD copper_reset(void);
void copper_activate();
void copper_restore();
void copper_setColorValue(unsigned short index, unsigned short value);
void copper_setBitPlane(unsigned short index, unsigned short value);
void copper_setSpritePointer(unsigned short *sprite, char spriteIndex);
void copper_setBPLCON1(UWORD value);
void copper_setBPLCON2(UWORD value);
void copper_setValue(unsigned short index, unsigned short value);
void copper_setExtention(unsigned short index, unsigned short value);
UWORD copper_start(void);
UWORD copper_getExtentionIndex();
void copper_setExtentionIndex(UWORD index);
UWORD copper_waitForLine(UWORD line);
UWORD copper_setColor(UWORD index, UWORD color);
UWORD copper_end(void);
void copper_setGrid();
void copper_setGridValue(UWORD value, UWORD index);
void copper_setGridColor(UBYTE g);
void copper_setGridColors(UWORD *screen);
void copper_setGridScreen(UWORD *screen, UBYTE *fixed);
void copper_setGrid2Colors(UBYTE *screen);
void copper_setIntro(void);
UWORD* copper_getCopperList();